spring:
  datasource:
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 20000
  jpa:
    open-in-view: false
  thymeleaf:
    cache: true

server:
  forward-headers-strategy: framework
