services:
  - type: web
    name: book-exchange-platform
    runtime: docker
    plan: free
    autoDeployTrigger: commit
    healthCheckPath: /login
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: book-exchange-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: book-exchange-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: book-exchange-db
          property: password

databases:
  - name: book-exchange-db
    plan: free
    databaseName: book_exchange_db
    user: book_exchange_user
